// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;

namespace Microsoft.PowerBI.Api.Models
{
    /// <summary> Odata response wrapper for a Power BI service principal profile collection. </summary>
    public partial class AdminServicePrincipalProfiles
    {
        /// <summary> Initializes a new instance of <see cref="AdminServicePrincipalProfiles"/>. </summary>
        internal AdminServicePrincipalProfiles()
        {
            Value = new ChangeTrackingList<AdminServicePrincipalProfile>();
        }

        /// <summary> Initializes a new instance of <see cref="AdminServicePrincipalProfiles"/>. </summary>
        /// <param name="odataContext"> OData context. </param>
        /// <param name="value"> The service principal profile collection. </param>
        internal AdminServicePrincipalProfiles(string odataContext, IReadOnlyList<AdminServicePrincipalProfile> value)
        {
            OdataContext = odataContext;
            Value = value;
        }

        /// <summary> OData context. </summary>
        public string OdataContext { get; }
        /// <summary> The service principal profile collection. </summary>
        public IReadOnlyList<AdminServicePrincipalProfile> Value { get; }
    }
}
