// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace Microsoft.PowerBI.Api.Models
{
    /// <summary> A Power BI service principal profile. Only relevant for [Power BI Embedded multi-tenancy solution](/power-bi/developer/embedded/embed-multi-tenancy). </summary>
    public partial class AdminServicePrincipalProfile : ServicePrincipalProfile
    {
        /// <summary> Initializes a new instance of <see cref="AdminServicePrincipalProfile"/>. </summary>
        /// <param name="id"> The service principal profile ID. </param>
        public AdminServicePrincipalProfile(Guid id) : base(id)
        {
        }

        /// <summary> Initializes a new instance of <see cref="AdminServicePrincipalProfile"/>. </summary>
        /// <param name="id"> The service principal profile ID. </param>
        /// <param name="displayName"> The service principal profile name. </param>
        /// <param name="servicePrincipalId"> The service principal ID. </param>
        internal AdminServicePrincipalProfile(Guid id, string displayName, Guid? servicePrincipalId) : base(id, displayName)
        {
            ServicePrincipalId = servicePrincipalId;
        }

        /// <summary> The service principal ID. </summary>
        public Guid? ServicePrincipalId { get; set; }
    }
}
