// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;

namespace Microsoft.PowerBI.Api.Models
{
    /// <summary> OData response wrapper for a Power BI Admin report collection. </summary>
    public partial class AdminReports
    {
        /// <summary> Initializes a new instance of <see cref="AdminReports"/>. </summary>
        internal AdminReports()
        {
            Value = new ChangeTrackingList<AdminReport>();
        }

        /// <summary> Initializes a new instance of <see cref="AdminReports"/>. </summary>
        /// <param name="odataContext"> OData context. </param>
        /// <param name="value"> The report collection. </param>
        internal AdminReports(string odataContext, IReadOnlyList<AdminReport> value)
        {
            OdataContext = odataContext;
            Value = value;
        }

        /// <summary> OData context. </summary>
        public string OdataContext { get; }
        /// <summary> The report collection. </summary>
        public IReadOnlyList<AdminReport> Value { get; }
    }
}
