// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Microsoft.PowerBI.Api.Models
{
    /// <summary> The access right that the user has for the app. </summary>
    public enum AppUserAccessRight
    {
        /// <summary> No permission to content in app. </summary>
        None,
        /// <summary> Grants Read access to content in app. </summary>
        Read,
        /// <summary> Grants Read and Write access to content in app. </summary>
        ReadWrite,
        /// <summary> Grants Read and Reshare access to content in app. </summary>
        ReadReshare,
        /// <summary> Grants Read, Write and Reshare access to content in app. </summary>
        ReadWriteReshare,
        /// <summary> Grants Read and Explore access to content in app. </summary>
        ReadExplore,
        /// <summary> Grants Read and Copy access to content in app. </summary>
        ReadCopy,
        /// <summary> Grants Read, Explore and Copy access to content in app. </summary>
        ReadExploreCopy,
        /// <summary> Grants Read, Reshare, Explore and Copy access to content in app. </summary>
        ReadReshareExploreCopy,
        /// <summary> Grants Read, Reshare and Explore access to content in app. </summary>
        ReadReshareExplore,
        /// <summary> Grants Read, Write and Explore access to content in app. </summary>
        ReadWriteExplore,
        /// <summary> Grants Read, Write, Reshare and Explore access to content in app. </summary>
        ReadWriteReshareExplore,
        /// <summary> Grants Read, Write, Explore and Copy access to content in app. </summary>
        ReadWriteExploreCopy,
        /// <summary> Grants Read, Reshare, and Copy access to content in app. </summary>
        ReadReshareCopy,
        /// <summary> Grants Read, Write, Explore, Reshare and Copy access to content in app. </summary>
        All
    }
}
