// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace Microsoft.PowerBI.Api.Models
{
    /// <summary> The unique ID of a Power BI item in UUID format. Dashboard, report, and dataflow IDs are in UUID format, and dataset IDs can be in UUID or string format. </summary>
    public partial class ArtifactId
    {
        /// <summary> Initializes a new instance of <see cref="ArtifactId"/>. </summary>
        /// <param name="id"> An ID in UUID format. </param>
        public ArtifactId(Guid id)
        {
            Id = id;
        }

        /// <summary> An ID in UUID format. </summary>
        public Guid Id { get; }
    }
}
