// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace Microsoft.PowerBI.Api.Models
{
    /// <summary> The unique ID of a Power BI item in string or UUID format. Dashboard, report, and dataflow IDs are in UUID format, and dataset IDs can be in UUID or string format. </summary>
    public partial class ArtifactStringId
    {
        /// <summary> Initializes a new instance of <see cref="ArtifactStringId"/>. </summary>
        /// <param name="id"> An ID in string or UUID format. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="id"/> is null. </exception>
        public ArtifactStringId(string id)
        {
            Argument.AssertNotNull(id, nameof(id));

            Id = id;
        }

        /// <summary> An ID in string or UUID format. </summary>
        public string Id { get; }
    }
}
