// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace Microsoft.PowerBI.Api.Models
{
    /// <summary> A Power BI assign to dataflow storage account request. </summary>
    public partial class AssignToDataflowStorageRequest
    {
        /// <summary> Initializes a new instance of <see cref="AssignToDataflowStorageRequest"/>. </summary>
        /// <param name="dataflowStorageId"> The Power BI dataflow storage account ID. To unassign the specified workspace from a Power BI dataflow storage account, use an empty GUID (`00000000-0000-0000-0000-000000000000`). </param>
        public AssignToDataflowStorageRequest(Guid dataflowStorageId)
        {
            DataflowStorageId = dataflowStorageId;
        }

        /// <summary> The Power BI dataflow storage account ID. To unassign the specified workspace from a Power BI dataflow storage account, use an empty GUID (`00000000-0000-0000-0000-000000000000`). </summary>
        public Guid DataflowStorageId { get; }
    }
}
