// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;

namespace Microsoft.PowerBI.Api.Models
{
    /// <summary> A request to assign workspaces to a premium capacity. </summary>
    public partial class AssignWorkspacesToCapacityRequest
    {
        /// <summary> Initializes a new instance of <see cref="AssignWorkspacesToCapacityRequest"/>. </summary>
        public AssignWorkspacesToCapacityRequest()
        {
            CapacityMigrationAssignments = new ChangeTrackingList<CapacityMigrationAssignment>();
        }

        /// <summary> Initializes a new instance of <see cref="AssignWorkspacesToCapacityRequest"/>. </summary>
        /// <param name="capacityMigrationAssignments"></param>
        internal AssignWorkspacesToCapacityRequest(IList<CapacityMigrationAssignment> capacityMigrationAssignments)
        {
            CapacityMigrationAssignments = capacityMigrationAssignments;
        }

        /// <summary> Gets the capacity migration assignments. </summary>
        public IList<CapacityMigrationAssignment> CapacityMigrationAssignments { get; }
    }
}
