// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;

namespace Microsoft.PowerBI.Api.Models
{
    /// <summary> OData response wrapper for a Power BI available features list. </summary>
    public partial class AvailableFeatures
    {
        /// <summary> Initializes a new instance of <see cref="AvailableFeatures"/>. </summary>
        internal AvailableFeatures()
        {
            Features = new ChangeTrackingList<AvailableFeature>();
        }

        /// <summary> Initializes a new instance of <see cref="AvailableFeatures"/>. </summary>
        /// <param name="odataContext"></param>
        /// <param name="features"> The available features list. </param>
        internal AvailableFeatures(string odataContext, IReadOnlyList<AvailableFeature> features)
        {
            OdataContext = odataContext;
            Features = features;
        }

        /// <summary> Gets the odata context. </summary>
        public string OdataContext { get; }
        /// <summary> The available features list. </summary>
        public IReadOnlyList<AvailableFeature> Features { get; }
    }
}
