// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;

namespace Microsoft.PowerBI.Api.Models
{
    /// <summary> The bind dataset to gateway request. </summary>
    public partial class BindToGatewayRequest
    {
        /// <summary> Initializes a new instance of <see cref="BindToGatewayRequest"/>. </summary>
        /// <param name="gatewayObjectId"> The gateway ID. When using a gateway cluster, the gateway ID refers to the primary (first) gateway in the cluster and is similar to the gateway cluster ID. </param>
        public BindToGatewayRequest(Guid gatewayObjectId)
        {
            GatewayObjectId = gatewayObjectId;
            DatasourceObjectIds = new ChangeTrackingList<Guid>();
        }

        /// <summary> Initializes a new instance of <see cref="BindToGatewayRequest"/>. </summary>
        /// <param name="gatewayObjectId"> The gateway ID. When using a gateway cluster, the gateway ID refers to the primary (first) gateway in the cluster and is similar to the gateway cluster ID. </param>
        /// <param name="datasourceObjectIds"> The unique identifiers for the data sources in the gateway. </param>
        internal BindToGatewayRequest(Guid gatewayObjectId, IList<Guid> datasourceObjectIds)
        {
            GatewayObjectId = gatewayObjectId;
            DatasourceObjectIds = datasourceObjectIds;
        }

        /// <summary> The gateway ID. When using a gateway cluster, the gateway ID refers to the primary (first) gateway in the cluster and is similar to the gateway cluster ID. </summary>
        public Guid GatewayObjectId { get; }
        /// <summary> The unique identifiers for the data sources in the gateway. </summary>
        public IList<Guid> DatasourceObjectIds { get; }
    }
}
