// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Microsoft.PowerBI.Api.Models
{
    /// <summary> The capacity state. </summary>
    public enum CapacityState
    {
        /// <summary> Unsupported. </summary>
        NotActivated,
        /// <summary> The capacity is ready to use. </summary>
        Active,
        /// <summary> Activation of the capacity is in progress. </summary>
        Provisioning,
        /// <summary> Provisioning of the capacity failed. </summary>
        ProvisionFailed,
        /// <summary> Use of the capacity is suspended. </summary>
        Suspended,
        /// <summary> Unsupported. </summary>
        PreSuspended,
        /// <summary> Deletion of the capacity is in progress. </summary>
        Deleting,
        /// <summary> The capacity was deleted and is unavailable. </summary>
        Deleted,
        /// <summary> The capacity can't be used. </summary>
        Invalid,
        /// <summary> A capacity SKU change is in progress. </summary>
        UpdatingSku
    }
}
