// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace Microsoft.PowerBI.Api.Models
{
    /// <summary> A request to create a new deployment pipeline. </summary>
    public partial class CreatePipelineRequest
    {
        /// <summary> Initializes a new instance of <see cref="CreatePipelineRequest"/>. </summary>
        /// <param name="displayName"> The display name for the new deployment pipeline. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="displayName"/> is null. </exception>
        public CreatePipelineRequest(string displayName)
        {
            Argument.AssertNotNull(displayName, nameof(displayName));

            DisplayName = displayName;
        }

        /// <summary> Initializes a new instance of <see cref="CreatePipelineRequest"/>. </summary>
        /// <param name="displayName"> The display name for the new deployment pipeline. </param>
        /// <param name="description"> The description for the new deployment pipeline. </param>
        internal CreatePipelineRequest(string displayName, string description)
        {
            DisplayName = displayName;
            Description = description;
        }

        /// <summary> The display name for the new deployment pipeline. </summary>
        public string DisplayName { get; }
        /// <summary> The description for the new deployment pipeline. </summary>
        public string Description { get; set; }
    }
}
