// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace Microsoft.PowerBI.Api.Models
{
    public partial class CredentialDetails : IUtf8JsonSerializable
    {
        void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            writer.WritePropertyName("credentials"u8);
            writer.WriteStringValue(Credentials);
            writer.WritePropertyName("credentialType"u8);
            writer.WriteStringValue(CredentialType.ToSerialString());
            writer.WritePropertyName("encryptedConnection"u8);
            writer.WriteStringValue(EncryptedConnection.ToSerialString());
            writer.WritePropertyName("encryptionAlgorithm"u8);
            writer.WriteStringValue(EncryptionAlgorithm.ToSerialString());
            writer.WritePropertyName("privacyLevel"u8);
            writer.WriteStringValue(PrivacyLevel.ToSerialString());
            if (Optional.IsDefined(UseCallerAADIdentity))
            {
                writer.WritePropertyName("useCallerAADIdentity"u8);
                writer.WriteBooleanValue(UseCallerAADIdentity.Value);
            }
            if (Optional.IsDefined(UseEndUserOAuth2Credentials))
            {
                writer.WritePropertyName("useEndUserOAuth2Credentials"u8);
                writer.WriteBooleanValue(UseEndUserOAuth2Credentials.Value);
            }
            writer.WriteEndObject();
        }

        /// <summary> Convert into a <see cref="RequestContent"/>. </summary>
        internal virtual RequestContent ToRequestContent()
        {
            var content = new Utf8JsonRequestContent();
            content.JsonWriter.WriteObjectValue(this);
            return content;
        }
    }
}
