// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace Microsoft.PowerBI.Api.Models
{
    /// <summary> Power BI dashboard common properties. The API returns a subset of the following list of report properties. The subset depends on the API called, caller permissions, and the availability of data in the Power BI database. </summary>
    public partial class DashboardBaseProperties
    {
        /// <summary> Initializes a new instance of <see cref="DashboardBaseProperties"/>. </summary>
        /// <param name="id"> The dashboard ID. </param>
        public DashboardBaseProperties(Guid id)
        {
            Id = id;
        }

        /// <summary> Initializes a new instance of <see cref="DashboardBaseProperties"/>. </summary>
        /// <param name="id"> The dashboard ID. </param>
        /// <param name="displayName"> The display name of the dashboard. </param>
        /// <param name="isReadOnly"> Whether the dashboard is read-only. </param>
        /// <param name="appId"> The app ID, returned only if the dashboard belongs to an app. </param>
        internal DashboardBaseProperties(Guid id, string displayName, bool? isReadOnly, string appId)
        {
            Id = id;
            DisplayName = displayName;
            IsReadOnly = isReadOnly;
            AppId = appId;
        }

        /// <summary> The dashboard ID. </summary>
        public Guid Id { get; set; }
        /// <summary> The display name of the dashboard. </summary>
        public string DisplayName { get; set; }
        /// <summary> Whether the dashboard is read-only. </summary>
        public bool? IsReadOnly { get; set; }
        /// <summary> The app ID, returned only if the dashboard belongs to an app. </summary>
        public string AppId { get; set; }
    }
}
