// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Microsoft.PowerBI.Api.Models
{
    /// <summary> The access right that the user has for the dashboard (permission level). </summary>
    public enum DashboardUserAccessRight
    {
        /// <summary> No permission to content in dashboard. </summary>
        None,
        /// <summary> Grants Read access to content in dashboard. </summary>
        Read,
        /// <summary> Grants Read and Write access to content in dashboard. </summary>
        ReadWrite,
        /// <summary> Grants Read and Reshare access to content in dashboard. </summary>
        ReadReshare,
        /// <summary> Grants Read and Copy access to content in dashboard. </summary>
        ReadCopy,
        /// <summary> Grants Read, Write and Reshare access to content in report. </summary>
        Owner
    }
}
