// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Microsoft.PowerBI.Api.Models
{
    /// <summary> The details of the information protection label, if any, associated with the dataset. </summary>
    public partial class DatasetExecuteQueriesInformationProtectionLabel
    {
        /// <summary> Initializes a new instance of <see cref="DatasetExecuteQueriesInformationProtectionLabel"/>. </summary>
        internal DatasetExecuteQueriesInformationProtectionLabel()
        {
        }

        /// <summary> Initializes a new instance of <see cref="DatasetExecuteQueriesInformationProtectionLabel"/>. </summary>
        /// <param name="id"> The identifier (guid) of the information protection label. </param>
        /// <param name="name"> The display name of the information protection label. </param>
        internal DatasetExecuteQueriesInformationProtectionLabel(string id, string name)
        {
            Id = id;
            Name = name;
        }

        /// <summary> The identifier (guid) of the information protection label. </summary>
        public string Id { get; }
        /// <summary> The display name of the information protection label. </summary>
        public string Name { get; }
    }
}
