// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Microsoft.PowerBI.Api.Models
{
    /// <summary> Power BI dataset refresh target. </summary>
    public partial class DatasetRefreshObjects
    {
        /// <summary> Initializes a new instance of <see cref="DatasetRefreshObjects"/>. </summary>
        public DatasetRefreshObjects()
        {
        }

        /// <summary> Initializes a new instance of <see cref="DatasetRefreshObjects"/>. </summary>
        /// <param name="table"> Table to refresh. </param>
        /// <param name="partition"> Partition to refresh. </param>
        internal DatasetRefreshObjects(string table, string partition)
        {
            Table = table;
            Partition = partition;
        }

        /// <summary> Table to refresh. </summary>
        public string Table { get; set; }
        /// <summary> Partition to refresh. </summary>
        public string Partition { get; set; }
    }
}
