// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure;

namespace Microsoft.PowerBI.Api.Models
{
    public partial class DatasetToDataflowLinkResponse
    {
        internal static DatasetToDataflowLinkResponse DeserializeDatasetToDataflowLinkResponse(JsonElement element)
        {
            if (element.ValueKind == JsonValueKind.Null)
            {
                return null;
            }
            string datasetObjectId = default;
            string dataflowObjectId = default;
            string workspaceObjectId = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("datasetObjectId"u8))
                {
                    datasetObjectId = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("dataflowObjectId"u8))
                {
                    dataflowObjectId = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("workspaceObjectId"u8))
                {
                    workspaceObjectId = property.Value.GetString();
                    continue;
                }
            }
            return new DatasetToDataflowLinkResponse(datasetObjectId, dataflowObjectId, workspaceObjectId);
        }

        /// <summary> Deserializes the model from a raw response. </summary>
        /// <param name="response"> The response to deserialize the model from. </param>
        internal static DatasetToDataflowLinkResponse FromResponse(Response response)
        {
            using var document = JsonDocument.Parse(response.Content);
            return DeserializeDatasetToDataflowLinkResponse(document.RootElement);
        }
    }
}
