// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;
using System.Text.Json;
using Azure;

namespace Microsoft.PowerBI.Api.Models
{
    public partial class DatamartUpstreamProperties
    {
        internal static DatamartUpstreamProperties DeserializeDatamartUpstreamProperties(JsonElement element)
        {
            if (element.ValueKind == JsonValueKind.Null)
            {
                return null;
            }
            IReadOnlyList<DependentDataflow> upstreamDataflows = default;
            IReadOnlyList<DependentDatamart> upstreamDatamarts = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("upstreamDataflows"u8))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        continue;
                    }
                    List<DependentDataflow> array = new List<DependentDataflow>();
                    foreach (var item in property.Value.EnumerateArray())
                    {
                        array.Add(DependentDataflow.DeserializeDependentDataflow(item));
                    }
                    upstreamDataflows = array;
                    continue;
                }
                if (property.NameEquals("upstreamDatamarts"u8))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        continue;
                    }
                    List<DependentDatamart> array = new List<DependentDatamart>();
                    foreach (var item in property.Value.EnumerateArray())
                    {
                        array.Add(DependentDatamart.DeserializeDependentDatamart(item));
                    }
                    upstreamDatamarts = array;
                    continue;
                }
            }
            return new DatamartUpstreamProperties(upstreamDataflows ?? new ChangeTrackingList<DependentDataflow>(), upstreamDatamarts ?? new ChangeTrackingList<DependentDatamart>());
        }

        /// <summary> Deserializes the model from a raw response. </summary>
        /// <param name="response"> The response to deserialize the model from. </param>
        internal static DatamartUpstreamProperties FromResponse(Response response)
        {
            using var document = JsonDocument.Parse(response.Content);
            return DeserializeDatamartUpstreamProperties(document.RootElement);
        }
    }
}
