// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Microsoft.PowerBI.Api.Models
{
    /// <summary> The datamart status. </summary>
    public enum DatamartStatus
    {
        /// <summary> The datamart has invalid status. </summary>
        Invalid,
        /// <summary> The datamart is available. </summary>
        Available,
        /// <summary> The datamart is suspended in critical phase. </summary>
        SuspendedInCriticalPhase,
        /// <summary> The datamart is in progress. </summary>
        InProgress,
        /// <summary> The datamart has error status. </summary>
        Error,
        /// <summary> The datamart is out of region. </summary>
        OutOfRegion,
        /// <summary> The datamart has no capacity. </summary>
        NoCapacity
    }
}
