// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace Microsoft.PowerBI.Api.Models
{
    /// <summary> A Power BI data source. </summary>
    public partial class Datasource
    {
        /// <summary> Initializes a new instance of <see cref="Datasource"/>. </summary>
        public Datasource()
        {
        }

        /// <summary> Initializes a new instance of <see cref="Datasource"/>. </summary>
        /// <param name="name"> (Deprecated) The data source name. Available only for DirectQuery. </param>
        /// <param name="connectionString"> (Deprecated) The data source connection string. Available only for DirectQuery. </param>
        /// <param name="datasourceType"> The data source type. </param>
        /// <param name="connectionDetails"> The data source connection details. </param>
        /// <param name="gatewayId"> The bound gateway ID, which is empty when not bound to a gateway. When using a gateway cluster, the gateway ID refers to the primary (first) gateway in the cluster and is similar to the gateway cluster ID. </param>
        /// <param name="datasourceId"> The bound data source ID, which is empty when not bound to a gateway. </param>
        internal Datasource(string name, string connectionString, string datasourceType, DatasourceConnectionDetails connectionDetails, Guid? gatewayId, Guid? datasourceId)
        {
            Name = name;
            ConnectionString = connectionString;
            DatasourceType = datasourceType;
            ConnectionDetails = connectionDetails;
            GatewayId = gatewayId;
            DatasourceId = datasourceId;
        }

        /// <summary> (Deprecated) The data source name. Available only for DirectQuery. </summary>
        public string Name { get; set; }
        /// <summary> (Deprecated) The data source connection string. Available only for DirectQuery. </summary>
        public string ConnectionString { get; set; }
        /// <summary> The data source type. </summary>
        public string DatasourceType { get; set; }
        /// <summary> The data source connection details. </summary>
        public DatasourceConnectionDetails ConnectionDetails { get; set; }
        /// <summary> The bound gateway ID, which is empty when not bound to a gateway. When using a gateway cluster, the gateway ID refers to the primary (first) gateway in the cluster and is similar to the gateway cluster ID. </summary>
        public Guid? GatewayId { get; set; }
        /// <summary> The bound data source ID, which is empty when not bound to a gateway. </summary>
        public Guid? DatasourceId { get; set; }
    }
}
