// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace Microsoft.PowerBI.Api.Models
{
    /// <summary> A dataset query. </summary>
    public partial class DatasetExecuteQueriesQuery
    {
        /// <summary> Initializes a new instance of <see cref="DatasetExecuteQueriesQuery"/>. </summary>
        /// <param name="query"> The DAX query to be executed. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="query"/> is null. </exception>
        public DatasetExecuteQueriesQuery(string query)
        {
            Argument.AssertNotNull(query, nameof(query));

            Query = query;
        }

        /// <summary> The DAX query to be executed. </summary>
        public string Query { get; }
    }
}
