// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Microsoft.PowerBI.Api.Models
{
    /// <summary> A Power BI dataset to dataflow link. </summary>
    public partial class DatasetToDataflowLinkResponse
    {
        /// <summary> Initializes a new instance of <see cref="DatasetToDataflowLinkResponse"/>. </summary>
        internal DatasetToDataflowLinkResponse()
        {
        }

        /// <summary> Initializes a new instance of <see cref="DatasetToDataflowLinkResponse"/>. </summary>
        /// <param name="datasetObjectId"> The dataset object ID. </param>
        /// <param name="dataflowObjectId"> The dataflow object ID. </param>
        /// <param name="workspaceObjectId"> The workspace object ID. </param>
        internal DatasetToDataflowLinkResponse(string datasetObjectId, string dataflowObjectId, string workspaceObjectId)
        {
            DatasetObjectId = datasetObjectId;
            DataflowObjectId = dataflowObjectId;
            WorkspaceObjectId = workspaceObjectId;
        }

        /// <summary> The dataset object ID. </summary>
        public string DatasetObjectId { get; }
        /// <summary> The dataflow object ID. </summary>
        public string DataflowObjectId { get; }
        /// <summary> The workspace object ID. </summary>
        public string WorkspaceObjectId { get; }
    }
}
