// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Microsoft.PowerBI.Api.Models
{
    /// <summary> A Power BI dependent dataflow. </summary>
    public partial class DependentDataflow
    {
        /// <summary> Initializes a new instance of <see cref="DependentDataflow"/>. </summary>
        public DependentDataflow()
        {
        }

        /// <summary> Initializes a new instance of <see cref="DependentDataflow"/>. </summary>
        /// <param name="targetDataflowId"> The target dataflow ID. </param>
        /// <param name="groupId"> The target group ID. </param>
        internal DependentDataflow(string targetDataflowId, string groupId)
        {
            TargetDataflowId = targetDataflowId;
            GroupId = groupId;
        }

        /// <summary> The target dataflow ID. </summary>
        public string TargetDataflowId { get; set; }
        /// <summary> The target group ID. </summary>
        public string GroupId { get; set; }
    }
}
