// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Microsoft.PowerBI.Api.Models
{
    /// <summary> A Power BI dependent datamart. </summary>
    public partial class DependentDatamart
    {
        /// <summary> Initializes a new instance of <see cref="DependentDatamart"/>. </summary>
        public DependentDatamart()
        {
        }

        /// <summary> Initializes a new instance of <see cref="DependentDatamart"/>. </summary>
        /// <param name="targetDatamartId"> The target datamart ID. </param>
        /// <param name="groupId"> The target group ID. </param>
        internal DependentDatamart(string targetDatamartId, string groupId)
        {
            TargetDatamartId = targetDatamartId;
            GroupId = groupId;
        }

        /// <summary> The target datamart ID. </summary>
        public string TargetDatamartId { get; set; }
        /// <summary> The target group ID. </summary>
        public string GroupId { get; set; }
    }
}
