// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace Microsoft.PowerBI.Api.Models
{
    /// <summary> Power BI refresh schedule request for DirectQuery or LiveConnection. </summary>
    public partial class DirectQueryRefreshScheduleRequest
    {
        /// <summary> Initializes a new instance of <see cref="DirectQueryRefreshScheduleRequest"/>. </summary>
        /// <param name="value"> An object containing the refresh schedule details for DirectQuery or LiveConnection. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="value"/> is null. </exception>
        public DirectQueryRefreshScheduleRequest(DirectQueryRefreshSchedule value)
        {
            Argument.AssertNotNull(value, nameof(value));

            Value = value;
        }

        /// <summary> An object containing the refresh schedule details for DirectQuery or LiveConnection. </summary>
        public DirectQueryRefreshSchedule Value { get; }
    }
}
