// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Microsoft.PowerBI.Api.Models
{
    /// <summary> Whether to encrypt the data source connection. The API call will fail if you select encryption and Power BI is unable to establish an encrypted connection with the data source. </summary>
    public enum EncryptedConnection
    {
        /// <summary> Encrypted. </summary>
        Encrypted,
        /// <summary> NotEncrypted. </summary>
        NotEncrypted
    }
}
