// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Microsoft.PowerBI.Api.Models
{
    /// <summary> Dataset encryption status. </summary>
    public enum EncryptionStatus
    {
        /// <summary> The encryption status is unknown due to dataset corruption. </summary>
        Unknown,
        /// <summary> Encryption isn't supported for this dataset. </summary>
        NotSupported,
        /// <summary> Encryption is supported and is in sync with the encryption settings. </summary>
        InSyncWithWorkspace,
        /// <summary> Encryption is supported but isn't in sync with the encryption settings. </summary>
        NotInSyncWithWorkspace
    }
}
