// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Microsoft.PowerBI.Api.Models
{
    /// <summary> The error or warning message from engine for enhanced refresh. </summary>
    public partial class EngineMessage
    {
        /// <summary> Initializes a new instance of <see cref="EngineMessage"/>. </summary>
        internal EngineMessage()
        {
        }

        /// <summary> Initializes a new instance of <see cref="EngineMessage"/>. </summary>
        /// <param name="code"> The error code in hex format. </param>
        /// <param name="message"> The text of error or warning message. </param>
        /// <param name="type"> The type of the error. </param>
        internal EngineMessage(string code, string message, RefreshEngineErrorType? type)
        {
            Code = code;
            Message = message;
            Type = type;
        }

        /// <summary> The error code in hex format. </summary>
        public string Code { get; }
        /// <summary> The text of error or warning message. </summary>
        public string Message { get; }
        /// <summary> The type of the error. </summary>
        public RefreshEngineErrorType? Type { get; }
    }
}
