// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Microsoft.PowerBI.Api.Models
{
    /// <summary> A filter to be applied during the export operation. </summary>
    public partial class ExportFilter
    {
        /// <summary> Initializes a new instance of <see cref="ExportFilter"/>. </summary>
        public ExportFilter()
        {
        }

        /// <summary> Initializes a new instance of <see cref="ExportFilter"/>. </summary>
        /// <param name="filter"> The filter to apply. For information about the filter syntax, see [Filter a report](/power-bi/collaborate-share/service-url-filters). </param>
        internal ExportFilter(string filter)
        {
            Filter = filter;
        }

        /// <summary> The filter to apply. For information about the filter syntax, see [Filter a report](/power-bi/collaborate-share/service-url-filters). </summary>
        public string Filter { get; set; }
    }
}
