// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure;

namespace Microsoft.PowerBI.Api.Models
{
    public partial class GatewayDatasourceCredentialDetails
    {
        internal static GatewayDatasourceCredentialDetails DeserializeGatewayDatasourceCredentialDetails(JsonElement element)
        {
            if (element.ValueKind == JsonValueKind.Null)
            {
                return null;
            }
            bool? useEndUserOAuth2Credentials = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("useEndUserOAuth2Credentials"u8))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        continue;
                    }
                    useEndUserOAuth2Credentials = property.Value.GetBoolean();
                    continue;
                }
            }
            return new GatewayDatasourceCredentialDetails(useEndUserOAuth2Credentials);
        }

        /// <summary> Deserializes the model from a raw response. </summary>
        /// <param name="response"> The response to deserialize the model from. </param>
        internal static GatewayDatasourceCredentialDetails FromResponse(Response response)
        {
            using var document = JsonDocument.Parse(response.Content);
            return DeserializeGatewayDatasourceCredentialDetails(document.RootElement);
        }
    }
}
