// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace Microsoft.PowerBI.Api.Models
{
    /// <summary> A container for JSON definitions of status rules on a Power BI goal. </summary>
    public partial class GoalsRulesGoalRulesContainer
    {
        /// <summary> Initializes a new instance of <see cref="GoalsRulesGoalRulesContainer"/>. </summary>
        public GoalsRulesGoalRulesContainer()
        {
        }

        /// <summary> Initializes a new instance of <see cref="GoalsRulesGoalRulesContainer"/>. </summary>
        /// <param name="scorecardObjectId"> The scorecard ID. </param>
        /// <param name="goalObjectId"> The goal ID. </param>
        /// <param name="lastModifiedTime"> The UTC time at last modification. </param>
        /// <param name="rules"> The list of rules. </param>
        internal GoalsRulesGoalRulesContainer(Guid? scorecardObjectId, Guid? goalObjectId, DateTimeOffset? lastModifiedTime, string rules)
        {
            ScorecardObjectId = scorecardObjectId;
            GoalObjectId = goalObjectId;
            LastModifiedTime = lastModifiedTime;
            Rules = rules;
        }

        /// <summary> The scorecard ID. </summary>
        public Guid? ScorecardObjectId { get; set; }
        /// <summary> The goal ID. </summary>
        public Guid? GoalObjectId { get; set; }
        /// <summary> The UTC time at last modification. </summary>
        public DateTimeOffset? LastModifiedTime { get; set; }
        /// <summary> The list of rules. </summary>
        public string Rules { get; set; }
    }
}
