// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Microsoft.PowerBI.Api.Models
{
    /// <summary> The comparison operator. </summary>
    public enum GoalRulesFieldComparisonKind
    {
        /// <summary> Are equal. </summary>
        Equal,
        /// <summary> Is greater than. </summary>
        GreaterThan,
        /// <summary> Is greater than or equal. </summary>
        GreaterThanOrEqual,
        /// <summary> Is less than. </summary>
        LessThan,
        /// <summary> Is less than or equal. </summary>
        LessThanOrEqual
    }
}
