// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Microsoft.PowerBI.Api.Models
{
    /// <summary> An entry defining a percentage of some target metric in a condition for Power BI goal status rule. </summary>
    public partial class GoalsRulesPercentOf
    {
        /// <summary> Initializes a new instance of <see cref="GoalsRulesPercentOf"/>. </summary>
        public GoalsRulesPercentOf()
        {
        }

        /// <summary> Initializes a new instance of <see cref="GoalsRulesPercentOf"/>. </summary>
        /// <param name="field"> The field for which the percent value is computed. </param>
        /// <param name="percent"> The percent value. </param>
        internal GoalsRulesPercentOf(string field, double? percent)
        {
            Field = field;
            Percent = percent;
        }

        /// <summary> The field for which the percent value is computed. </summary>
        public string Field { get; set; }
        /// <summary> The percent value. </summary>
        public double? Percent { get; set; }
    }
}
