// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Microsoft.PowerBI.Api.Models
{
    /// <summary> A Power BI goal status rule. </summary>
    public partial class GoalsRulesRuleCondition
    {
        /// <summary> Initializes a new instance of <see cref="GoalsRulesRuleCondition"/>. </summary>
        public GoalsRulesRuleCondition()
        {
        }

        /// <summary> Initializes a new instance of <see cref="GoalsRulesRuleCondition"/>. </summary>
        /// <param name="fieldComparison"> The field comparison definition when `expression` isn't defined. </param>
        /// <param name="expression"> The rule condition expression when `fieldComparison` isn't defined. </param>
        internal GoalsRulesRuleCondition(GoalsRulesFieldComparison fieldComparison, string expression)
        {
            FieldComparison = fieldComparison;
            Expression = expression;
        }

        /// <summary> The field comparison definition when `expression` isn't defined. </summary>
        public GoalsRulesFieldComparison FieldComparison { get; set; }
        /// <summary> The rule condition expression when `fieldComparison` isn't defined. </summary>
        public string Expression { get; set; }
    }
}
