// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace Microsoft.PowerBI.Api.Models
{
    internal static partial class GoalAggregationTypeExtensions
    {
        public static string ToSerialString(this GoalAggregationType value) => value switch
        {
            GoalAggregationType.Value => "Value",
            GoalAggregationType.Target => "Target",
            GoalAggregationType.Status => "Status",
            GoalAggregationType.Sparkline => "Sparkline",
            GoalAggregationType.Change => "Change",
            _ => throw new ArgumentOutOfRangeException(nameof(value), value, "Unknown GoalAggregationType value.")
        };

        public static GoalAggregationType ToGoalAggregationType(this string value)
        {
            if (StringComparer.OrdinalIgnoreCase.Equals(value, "Value")) return GoalAggregationType.Value;
            if (StringComparer.OrdinalIgnoreCase.Equals(value, "Target")) return GoalAggregationType.Target;
            if (StringComparer.OrdinalIgnoreCase.Equals(value, "Status")) return GoalAggregationType.Status;
            if (StringComparer.OrdinalIgnoreCase.Equals(value, "Sparkline")) return GoalAggregationType.Sparkline;
            if (StringComparer.OrdinalIgnoreCase.Equals(value, "Change")) return GoalAggregationType.Change;
            throw new ArgumentOutOfRangeException(nameof(value), value, "Unknown GoalAggregationType value.");
        }
    }
}
