// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace Microsoft.PowerBI.Api.Models
{
    internal static partial class GoalValueTypeExtensions
    {
        public static string ToSerialString(this GoalValueType value) => value switch
        {
            GoalValueType.Current => "Current",
            GoalValueType.Target => "Target",
            GoalValueType.Status => "Status",
            _ => throw new ArgumentOutOfRangeException(nameof(value), value, "Unknown GoalValueType value.")
        };

        public static GoalValueType ToGoalValueType(this string value)
        {
            if (StringComparer.OrdinalIgnoreCase.Equals(value, "Current")) return GoalValueType.Current;
            if (StringComparer.OrdinalIgnoreCase.Equals(value, "Target")) return GoalValueType.Target;
            if (StringComparer.OrdinalIgnoreCase.Equals(value, "Status")) return GoalValueType.Status;
            throw new ArgumentOutOfRangeException(nameof(value), value, "Unknown GoalValueType value.");
        }
    }
}
