// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;

namespace Microsoft.PowerBI.Api.Models
{
    /// <summary> The OData response wrapper for a Power BI goal collection. </summary>
    public partial class Goals
    {
        /// <summary> Initializes a new instance of <see cref="Goals"/>. </summary>
        internal Goals()
        {
            Value = new ChangeTrackingList<Goal>();
        }

        /// <summary> Initializes a new instance of <see cref="Goals"/>. </summary>
        /// <param name="odataContext"> OData context. </param>
        /// <param name="value"> The goal collection. </param>
        internal Goals(string odataContext, IReadOnlyList<Goal> value)
        {
            OdataContext = odataContext;
            Value = value;
        }

        /// <summary> OData context. </summary>
        public string OdataContext { get; }
        /// <summary> The goal collection. </summary>
        public IReadOnlyList<Goal> Value { get; }
    }
}
