// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace Microsoft.PowerBI.Api.Models
{
    /// <summary> A creation request for a Power BI goal value check-in. </summary>
    public partial class GoalValueCreateRequest
    {
        /// <summary> Initializes a new instance of <see cref="GoalValueCreateRequest"/>. </summary>
        /// <param name="timestamp"> The UTC timestamp of the goal value check-in. The time portion of the timestamp is zero. </param>
        public GoalValueCreateRequest(DateTimeOffset timestamp)
        {
            Timestamp = timestamp;
        }

        /// <summary> Initializes a new instance of <see cref="GoalValueCreateRequest"/>. </summary>
        /// <param name="timestamp"> The UTC timestamp of the goal value check-in. The time portion of the timestamp is zero. </param>
        /// <param name="value"> Optional. The current value of the goal. </param>
        /// <param name="target"> Optional. The target value of the goal. </param>
        /// <param name="trend"> Optional. The value trend of the goal. </param>
        /// <param name="forecast"> Optional. The value trend forecast of the goal. </param>
        /// <param name="status">
        /// Optional. The goal status ID.
        ///
        /// | ID | Description |
        /// |-|-|
        /// | 0 | Not started |
        /// | 1 | On track |
        /// | 2 | At risk |
        /// | 3 | Behind |
        /// | 4 | Overdue |
        /// | 5 | Completed |
        /// </param>
        internal GoalValueCreateRequest(DateTimeOffset timestamp, double? value, double? target, int? trend, double? forecast, int? status)
        {
            Timestamp = timestamp;
            Value = value;
            Target = target;
            Trend = trend;
            Forecast = forecast;
            Status = status;
        }

        /// <summary> The UTC timestamp of the goal value check-in. The time portion of the timestamp is zero. </summary>
        public DateTimeOffset Timestamp { get; }
        /// <summary> Optional. The current value of the goal. </summary>
        public double? Value { get; set; }
        /// <summary> Optional. The target value of the goal. </summary>
        public double? Target { get; set; }
        /// <summary> Optional. The value trend of the goal. </summary>
        public int? Trend { get; set; }
        /// <summary> Optional. The value trend forecast of the goal. </summary>
        public double? Forecast { get; set; }
        /// <summary>
        /// Optional. The goal status ID.
        ///
        /// | ID | Description |
        /// |-|-|
        /// | 0 | Not started |
        /// | 1 | On track |
        /// | 2 | At risk |
        /// | 3 | Behind |
        /// | 4 | Overdue |
        /// | 5 | Completed |
        /// </summary>
        public int? Status { get; set; }
    }
}
