// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;

namespace Microsoft.PowerBI.Api.Models
{
    /// <summary> A composite of Power BI item IDs for each item type. The IDs specify which Power BI items require an information protection label update. </summary>
    public partial class InformationProtectionArtifactsChangeLabel
    {
        /// <summary> Initializes a new instance of <see cref="InformationProtectionArtifactsChangeLabel"/>. </summary>
        public InformationProtectionArtifactsChangeLabel()
        {
            Dashboards = new ChangeTrackingList<ArtifactId>();
            Reports = new ChangeTrackingList<ArtifactId>();
            Datasets = new ChangeTrackingList<ArtifactStringId>();
            Dataflows = new ChangeTrackingList<ArtifactId>();
        }

        /// <summary> Initializes a new instance of <see cref="InformationProtectionArtifactsChangeLabel"/>. </summary>
        /// <param name="dashboards"> A list of unique dashboard IDs. </param>
        /// <param name="reports"> A list of unique report IDs. </param>
        /// <param name="datasets"> A list of unique dataset IDs. </param>
        /// <param name="dataflows"> A list of unique dataflow IDs. </param>
        internal InformationProtectionArtifactsChangeLabel(IList<ArtifactId> dashboards, IList<ArtifactId> reports, IList<ArtifactStringId> datasets, IList<ArtifactId> dataflows)
        {
            Dashboards = dashboards;
            Reports = reports;
            Datasets = datasets;
            Dataflows = dataflows;
        }

        /// <summary> A list of unique dashboard IDs. </summary>
        public IList<ArtifactId> Dashboards { get; }
        /// <summary> A list of unique report IDs. </summary>
        public IList<ArtifactId> Reports { get; }
        /// <summary> A list of unique dataset IDs. </summary>
        public IList<ArtifactStringId> Datasets { get; }
        /// <summary> A list of unique dataflow IDs. </summary>
        public IList<ArtifactId> Dataflows { get; }
    }
}
