// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;

namespace Microsoft.PowerBI.Api.Models
{
    /// <summary> A composite of the ID and information protection label change status for one or more Power BI items organized by type. </summary>
    public partial class InformationProtectionChangeLabelResponse
    {
        /// <summary> Initializes a new instance of <see cref="InformationProtectionChangeLabelResponse"/>. </summary>
        internal InformationProtectionChangeLabelResponse()
        {
            Dashboards = new ChangeTrackingList<ChangeLabelStatus>();
            Reports = new ChangeTrackingList<ChangeLabelStatus>();
            Dataflows = new ChangeTrackingList<ChangeLabelStatus>();
            Datasets = new ChangeTrackingList<ChangeLabelStatus>();
        }

        /// <summary> Initializes a new instance of <see cref="InformationProtectionChangeLabelResponse"/>. </summary>
        /// <param name="dashboards"> A list containing the unique ID and information protection label change status of one or more dashboards. </param>
        /// <param name="reports"> A list containing the unique ID and information protection label change status of one or more reports. </param>
        /// <param name="dataflows"> A list containing the unique ID and information protection label change status of one or more dataflows. </param>
        /// <param name="datasets"> A list containing the unique ID and information protection label change status of one or more datasets. </param>
        internal InformationProtectionChangeLabelResponse(IReadOnlyList<ChangeLabelStatus> dashboards, IReadOnlyList<ChangeLabelStatus> reports, IReadOnlyList<ChangeLabelStatus> dataflows, IReadOnlyList<ChangeLabelStatus> datasets)
        {
            Dashboards = dashboards;
            Reports = reports;
            Dataflows = dataflows;
            Datasets = datasets;
        }

        /// <summary> A list containing the unique ID and information protection label change status of one or more dashboards. </summary>
        public IReadOnlyList<ChangeLabelStatus> Dashboards { get; }
        /// <summary> A list containing the unique ID and information protection label change status of one or more reports. </summary>
        public IReadOnlyList<ChangeLabelStatus> Reports { get; }
        /// <summary> A list containing the unique ID and information protection label change status of one or more dataflows. </summary>
        public IReadOnlyList<ChangeLabelStatus> Dataflows { get; }
        /// <summary> A list containing the unique ID and information protection label change status of one or more datasets. </summary>
        public IReadOnlyList<ChangeLabelStatus> Datasets { get; }
    }
}
