// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace Microsoft.PowerBI.Api.Models
{
    /// <summary> A modified workspace. </summary>
    public partial class ModifiedWorkspace
    {
        /// <summary> Initializes a new instance of <see cref="ModifiedWorkspace"/>. </summary>
        /// <param name="id"> The workspace object ID. </param>
        internal ModifiedWorkspace(Guid id)
        {
            Id = id;
        }

        /// <summary> The workspace object ID. </summary>
        public Guid Id { get; }
    }
}
