// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Microsoft.PowerBI.Api.Models
{
    /// <summary> Data contract for paginated report parameters. </summary>
    public partial class ParameterValue
    {
        /// <summary> Initializes a new instance of <see cref="ParameterValue"/>. </summary>
        public ParameterValue()
        {
        }

        /// <summary> Initializes a new instance of <see cref="ParameterValue"/>. </summary>
        /// <param name="name"> The parameter name. </param>
        /// <param name="value"> The parameter value. </param>
        internal ParameterValue(string name, string value)
        {
            Name = name;
            Value = value;
        }

        /// <summary> The parameter name. </summary>
        public string Name { get; set; }
        /// <summary> The parameter value. </summary>
        public string Value { get; set; }
    }
}
