// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;

namespace Microsoft.PowerBI.Api.Models
{
    /// <summary> OData response wrapper for a collection of Power BI deployment pipeline operations. </summary>
    public partial class PipelineOperations
    {
        /// <summary> Initializes a new instance of <see cref="PipelineOperations"/>. </summary>
        internal PipelineOperations()
        {
            Value = new ChangeTrackingList<PipelineOperation>();
        }

        /// <summary> Initializes a new instance of <see cref="PipelineOperations"/>. </summary>
        /// <param name="odataContext"> OData context. </param>
        /// <param name="value"> The collection of deployment pipeline operations. </param>
        internal PipelineOperations(string odataContext, IReadOnlyList<PipelineOperation> value)
        {
            OdataContext = odataContext;
            Value = value;
        }

        /// <summary> OData context. </summary>
        public string OdataContext { get; }
        /// <summary> The collection of deployment pipeline operations. </summary>
        public IReadOnlyList<PipelineOperation> Value { get; }
    }
}
