// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace Microsoft.PowerBI.Api.Models
{
    internal static partial class PipelineOperationStatusExtensions
    {
        public static string ToSerialString(this PipelineOperationStatus value) => value switch
        {
            PipelineOperationStatus.NotStarted => "NotStarted",
            PipelineOperationStatus.Executing => "Executing",
            PipelineOperationStatus.Succeeded => "Succeeded",
            PipelineOperationStatus.Failed => "Failed",
            _ => throw new ArgumentOutOfRangeException(nameof(value), value, "Unknown PipelineOperationStatus value.")
        };

        public static PipelineOperationStatus ToPipelineOperationStatus(this string value)
        {
            if (StringComparer.OrdinalIgnoreCase.Equals(value, "NotStarted")) return PipelineOperationStatus.NotStarted;
            if (StringComparer.OrdinalIgnoreCase.Equals(value, "Executing")) return PipelineOperationStatus.Executing;
            if (StringComparer.OrdinalIgnoreCase.Equals(value, "Succeeded")) return PipelineOperationStatus.Succeeded;
            if (StringComparer.OrdinalIgnoreCase.Equals(value, "Failed")) return PipelineOperationStatus.Failed;
            throw new ArgumentOutOfRangeException(nameof(value), value, "Unknown PipelineOperationStatus value.");
        }
    }
}
