// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace Microsoft.PowerBI.Api.Models
{
    /// <summary> The configuration details for creating a new workspace. Required when deploying to a stage that has no assigned workspaces. </summary>
    public partial class PipelineNewWorkspaceRequest
    {
        /// <summary> Initializes a new instance of <see cref="PipelineNewWorkspaceRequest"/>. </summary>
        public PipelineNewWorkspaceRequest()
        {
        }

        /// <summary> Initializes a new instance of <see cref="PipelineNewWorkspaceRequest"/>. </summary>
        /// <param name="name"> The name of the new workspace. </param>
        /// <param name="capacityId"> The ID of the capacity that the new workspace will be assigned to. If unspecified and the API caller has permissions for the source stage workspace capacity, then that capacity will be used. Otherwise, Power BI will select a capacity that the API caller has permissions for. </param>
        internal PipelineNewWorkspaceRequest(string name, Guid? capacityId)
        {
            Name = name;
            CapacityId = capacityId;
        }

        /// <summary> The name of the new workspace. </summary>
        public string Name { get; set; }
        /// <summary> The ID of the capacity that the new workspace will be assigned to. If unspecified and the API caller has permissions for the source stage workspace capacity, then that capacity will be used. Otherwise, Power BI will select a capacity that the API caller has permissions for. </summary>
        public Guid? CapacityId { get; set; }
    }
}
