// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;

namespace Microsoft.PowerBI.Api.Models
{
    /// <summary> OData response wrapper for a collection of Power BI deployment pipeline users. </summary>
    public partial class PipelineUsers
    {
        /// <summary> Initializes a new instance of <see cref="PipelineUsers"/>. </summary>
        internal PipelineUsers()
        {
            Value = new ChangeTrackingList<PipelineUser>();
        }

        /// <summary> Initializes a new instance of <see cref="PipelineUsers"/>. </summary>
        /// <param name="odataContext"> OData context. </param>
        /// <param name="value"> The collection of deployment pipeline users. </param>
        internal PipelineUsers(string odataContext, IReadOnlyList<PipelineUser> value)
        {
            OdataContext = odataContext;
            Value = value;
        }

        /// <summary> OData context. </summary>
        public string OdataContext { get; }
        /// <summary> The collection of deployment pipeline users. </summary>
        public IReadOnlyList<PipelineUser> Value { get; }
    }
}
