// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Text.Json;
using Azure;

namespace Microsoft.PowerBI.Api.Models
{
    public partial class PipelineOperationUser
    {
        internal static PipelineOperationUser DeserializePipelineOperationUser(JsonElement element)
        {
            if (element.ValueKind == JsonValueKind.Null)
            {
                return null;
            }
            string userPrincipalName = default;
            Guid? principalObjectID = default;
            PrincipalType principalType = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("userPrincipalName"u8))
                {
                    userPrincipalName = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("principalObjectID"u8))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        continue;
                    }
                    principalObjectID = property.Value.GetGuid();
                    continue;
                }
                if (property.NameEquals("principalType"u8))
                {
                    principalType = property.Value.GetString().ToPrincipalType();
                    continue;
                }
            }
            return new PipelineOperationUser(userPrincipalName, principalObjectID, principalType);
        }

        /// <summary> Deserializes the model from a raw response. </summary>
        /// <param name="response"> The response to deserialize the model from. </param>
        internal static PipelineOperationUser FromResponse(Response response)
        {
            using var document = JsonDocument.Parse(response.Content);
            return DeserializePipelineOperationUser(document.RootElement);
        }
    }
}
