// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace Microsoft.PowerBI.Api.Models
{
    internal static partial class PositionConflictActionExtensions
    {
        public static string ToSerialString(this PositionConflictAction value) => value switch
        {
            PositionConflictAction.Tail => "Tail",
            PositionConflictAction.Abort => "Abort",
            _ => throw new ArgumentOutOfRangeException(nameof(value), value, "Unknown PositionConflictAction value.")
        };

        public static PositionConflictAction ToPositionConflictAction(this string value)
        {
            if (StringComparer.OrdinalIgnoreCase.Equals(value, "Tail")) return PositionConflictAction.Tail;
            if (StringComparer.OrdinalIgnoreCase.Equals(value, "Abort")) return PositionConflictAction.Abort;
            throw new ArgumentOutOfRangeException(nameof(value), value, "Unknown PositionConflictAction value.");
        }
    }
}
