// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace Microsoft.PowerBI.Api.Models
{
    internal static partial class PrincipalTypeExtensions
    {
        public static string ToSerialString(this PrincipalType value) => value switch
        {
            PrincipalType.None => "None",
            PrincipalType.User => "User",
            PrincipalType.Group => "Group",
            PrincipalType.App => "App",
            _ => throw new ArgumentOutOfRangeException(nameof(value), value, "Unknown PrincipalType value.")
        };

        public static PrincipalType ToPrincipalType(this string value)
        {
            if (StringComparer.OrdinalIgnoreCase.Equals(value, "None")) return PrincipalType.None;
            if (StringComparer.OrdinalIgnoreCase.Equals(value, "User")) return PrincipalType.User;
            if (StringComparer.OrdinalIgnoreCase.Equals(value, "Group")) return PrincipalType.Group;
            if (StringComparer.OrdinalIgnoreCase.Equals(value, "App")) return PrincipalType.App;
            throw new ArgumentOutOfRangeException(nameof(value), value, "Unknown PrincipalType value.");
        }
    }
}
