// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Microsoft.PowerBI.Api.Models
{
    /// <summary> The connection details for a paginated report data source. </summary>
    public partial class RdlDatasourceConnectionDetails
    {
        /// <summary> Initializes a new instance of <see cref="RdlDatasourceConnectionDetails"/>. </summary>
        public RdlDatasourceConnectionDetails()
        {
        }

        /// <summary> Initializes a new instance of <see cref="RdlDatasourceConnectionDetails"/>. </summary>
        /// <param name="server"> The connection server. </param>
        /// <param name="database"> The connection database. </param>
        internal RdlDatasourceConnectionDetails(string server, string database)
        {
            Server = server;
            Database = database;
        }

        /// <summary> The connection server. </summary>
        public string Server { get; set; }
        /// <summary> The connection database. </summary>
        public string Database { get; set; }
    }
}
