// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace Microsoft.PowerBI.Api.Models
{
    /// <summary> Power BI refresh schedule request. </summary>
    public partial class RefreshScheduleRequest
    {
        /// <summary> Initializes a new instance of <see cref="RefreshScheduleRequest"/>. </summary>
        /// <param name="value"> An object that contains the details of a refresh schedule. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="value"/> is null. </exception>
        public RefreshScheduleRequest(RefreshSchedule value)
        {
            Argument.AssertNotNull(value, nameof(value));

            Value = value;
        }

        /// <summary> An object that contains the details of a refresh schedule. </summary>
        public RefreshSchedule Value { get; }
    }
}
