// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace Microsoft.PowerBI.Api.Models
{
    /// <summary> A Power BI group associated to a Refreshable item. </summary>
    public partial class RefreshableGroup : GroupBaseProperties
    {
        /// <summary> Initializes a new instance of <see cref="RefreshableGroup"/>. </summary>
        /// <param name="id"> The workspace ID. </param>
        public RefreshableGroup(Guid id) : base(id)
        {
        }

        /// <summary> Initializes a new instance of <see cref="RefreshableGroup"/>. </summary>
        /// <param name="id"> The workspace ID. </param>
        /// <param name="name"> The group name. </param>
        internal RefreshableGroup(Guid id, string name) : base(id, name)
        {
        }
    }
}
