// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace Microsoft.PowerBI.Api.Models
{
    /// <summary> The RelatedDatasetProperties. </summary>
    public partial class RelatedDatasetProperties
    {
        /// <summary> Initializes a new instance of <see cref="RelatedDatasetProperties"/>. </summary>
        public RelatedDatasetProperties()
        {
        }

        /// <summary> Initializes a new instance of <see cref="RelatedDatasetProperties"/>. </summary>
        /// <param name="datasetWorkspaceId"> The workspace ID of the related dataset, returned only if the related dataset belongs to a different workspace. </param>
        internal RelatedDatasetProperties(Guid? datasetWorkspaceId)
        {
            DatasetWorkspaceId = datasetWorkspaceId;
        }

        /// <summary> The workspace ID of the related dataset, returned only if the related dataset belongs to a different workspace. </summary>
        public Guid? DatasetWorkspaceId { get; set; }
    }
}
