// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.ComponentModel;

namespace Microsoft.PowerBI.Api.Models
{
    /// <summary> The report type. </summary>
    public readonly partial struct ReportBasePropertiesReportType : IEquatable<ReportBasePropertiesReportType>
    {
        private readonly string _value;

        /// <summary> Initializes a new instance of <see cref="ReportBasePropertiesReportType"/>. </summary>
        /// <exception cref="ArgumentNullException"> <paramref name="value"/> is null. </exception>
        public ReportBasePropertiesReportType(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        private const string PaginatedReportValue = "PaginatedReport";
        private const string PowerBIReportValue = "PowerBIReport";

        /// <summary> PaginatedReport. </summary>
        public static ReportBasePropertiesReportType PaginatedReport { get; } = new ReportBasePropertiesReportType(PaginatedReportValue);
        /// <summary> PowerBIReport. </summary>
        public static ReportBasePropertiesReportType PowerBIReport { get; } = new ReportBasePropertiesReportType(PowerBIReportValue);
        /// <summary> Determines if two <see cref="ReportBasePropertiesReportType"/> values are the same. </summary>
        public static bool operator ==(ReportBasePropertiesReportType left, ReportBasePropertiesReportType right) => left.Equals(right);
        /// <summary> Determines if two <see cref="ReportBasePropertiesReportType"/> values are not the same. </summary>
        public static bool operator !=(ReportBasePropertiesReportType left, ReportBasePropertiesReportType right) => !left.Equals(right);
        /// <summary> Converts a string to a <see cref="ReportBasePropertiesReportType"/>. </summary>
        public static implicit operator ReportBasePropertiesReportType(string value) => new ReportBasePropertiesReportType(value);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object obj) => obj is ReportBasePropertiesReportType other && Equals(other);
        /// <inheritdoc />
        public bool Equals(ReportBasePropertiesReportType other) => string.Equals(_value, other._value, StringComparison.InvariantCultureIgnoreCase);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value != null ? StringComparer.InvariantCultureIgnoreCase.GetHashCode(_value) : 0;
        /// <inheritdoc />
        public override string ToString() => _value;
    }
}
