// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;

namespace Microsoft.PowerBI.Api.Models
{
    /// <summary> The OData response wrapper for a Power BI scorecard collection. </summary>
    public partial class Scorecards
    {
        /// <summary> Initializes a new instance of <see cref="Scorecards"/>. </summary>
        internal Scorecards()
        {
            Value = new ChangeTrackingList<Scorecard>();
        }

        /// <summary> Initializes a new instance of <see cref="Scorecards"/>. </summary>
        /// <param name="odataContext"> OData context. </param>
        /// <param name="odataCount"></param>
        /// <param name="odataNextLink"> Link to the next page results. </param>
        /// <param name="value"> The scorecard collection. </param>
        internal Scorecards(string odataContext, int? odataCount, string odataNextLink, IReadOnlyList<Scorecard> value)
        {
            OdataContext = odataContext;
            OdataCount = odataCount;
            OdataNextLink = odataNextLink;
            Value = value;
        }

        /// <summary> OData context. </summary>
        public string OdataContext { get; }
        /// <summary> Gets the odata count. </summary>
        public int? OdataCount { get; }
        /// <summary> Link to the next page results. </summary>
        public string OdataNextLink { get; }
        /// <summary> The scorecard collection. </summary>
        public IReadOnlyList<Scorecard> Value { get; }
    }
}
