// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;

namespace Microsoft.PowerBI.Api.Models
{
    /// <summary> OData response wrapper for a Power BI subscriptions. </summary>
    public partial class Subscriptions
    {
        /// <summary> Initializes a new instance of <see cref="Subscriptions"/>. </summary>
        internal Subscriptions()
        {
            Value = new ChangeTrackingList<Subscription>();
        }

        /// <summary> Initializes a new instance of <see cref="Subscriptions"/>. </summary>
        /// <param name="odataContext"></param>
        /// <param name="value"> Power BI email subscription. </param>
        internal Subscriptions(string odataContext, IReadOnlyList<Subscription> value)
        {
            OdataContext = odataContext;
            Value = value;
        }

        /// <summary> Gets the odata context. </summary>
        public string OdataContext { get; }
        /// <summary> Power BI email subscription. </summary>
        public IReadOnlyList<Subscription> Value { get; }
    }
}
