// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;

namespace Microsoft.PowerBI.Api.Models
{
    /// <summary> Encryption keys information. </summary>
    public partial class TenantKeys
    {
        /// <summary> Initializes a new instance of <see cref="TenantKeys"/>. </summary>
        internal TenantKeys()
        {
            Value = new ChangeTrackingList<TenantKey>();
        }

        /// <summary> Initializes a new instance of <see cref="TenantKeys"/>. </summary>
        /// <param name="odataContext"></param>
        /// <param name="value"> Encryption keys. </param>
        internal TenantKeys(string odataContext, IReadOnlyList<TenantKey> value)
        {
            OdataContext = odataContext;
            Value = value;
        }

        /// <summary> Gets the odata context. </summary>
        public string OdataContext { get; }
        /// <summary> Encryption keys. </summary>
        public IReadOnlyList<TenantKey> Value { get; }
    }
}
