// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Text.Json;
using Azure;
using Azure.Core;

namespace Microsoft.PowerBI.Api.Models
{
    public partial class Tile : IUtf8JsonSerializable
    {
        void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            if (Optional.IsDefined(RowSpan))
            {
                writer.WritePropertyName("rowSpan"u8);
                writer.WriteNumberValue(RowSpan.Value);
            }
            if (Optional.IsDefined(ColSpan))
            {
                writer.WritePropertyName("colSpan"u8);
                writer.WriteNumberValue(ColSpan.Value);
            }
            if (Optional.IsDefined(EmbedUrl))
            {
                writer.WritePropertyName("embedUrl"u8);
                writer.WriteStringValue(EmbedUrl);
            }
            if (Optional.IsDefined(EmbedData))
            {
                writer.WritePropertyName("embedData"u8);
                writer.WriteStringValue(EmbedData);
            }
            writer.WritePropertyName("id"u8);
            writer.WriteStringValue(Id);
            if (Optional.IsDefined(Title))
            {
                writer.WritePropertyName("title"u8);
                writer.WriteStringValue(Title);
            }
            if (Optional.IsDefined(ReportId))
            {
                writer.WritePropertyName("reportId"u8);
                writer.WriteStringValue(ReportId.Value);
            }
            if (Optional.IsDefined(DatasetId))
            {
                writer.WritePropertyName("datasetId"u8);
                writer.WriteStringValue(DatasetId);
            }
            writer.WriteEndObject();
        }

        internal static Tile DeserializeTile(JsonElement element)
        {
            if (element.ValueKind == JsonValueKind.Null)
            {
                return null;
            }
            int? rowSpan = default;
            int? colSpan = default;
            string embedUrl = default;
            string embedData = default;
            Guid id = default;
            string title = default;
            Guid? reportId = default;
            string datasetId = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("rowSpan"u8))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        continue;
                    }
                    rowSpan = property.Value.GetInt32();
                    continue;
                }
                if (property.NameEquals("colSpan"u8))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        continue;
                    }
                    colSpan = property.Value.GetInt32();
                    continue;
                }
                if (property.NameEquals("embedUrl"u8))
                {
                    embedUrl = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("embedData"u8))
                {
                    embedData = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("id"u8))
                {
                    id = property.Value.GetGuid();
                    continue;
                }
                if (property.NameEquals("title"u8))
                {
                    title = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("reportId"u8))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        continue;
                    }
                    reportId = property.Value.GetGuid();
                    continue;
                }
                if (property.NameEquals("datasetId"u8))
                {
                    datasetId = property.Value.GetString();
                    continue;
                }
            }
            return new Tile(
                id,
                title,
                reportId,
                datasetId,
                rowSpan,
                colSpan,
                embedUrl,
                embedData);
        }

        /// <summary> Deserializes the model from a raw response. </summary>
        /// <param name="response"> The response to deserialize the model from. </param>
        internal static new Tile FromResponse(Response response)
        {
            using var document = JsonDocument.Parse(response.Content);
            return DeserializeTile(document.RootElement);
        }

        /// <summary> Convert into a <see cref="RequestContent"/>. </summary>
        internal override RequestContent ToRequestContent()
        {
            var content = new Utf8JsonRequestContent();
            content.JsonWriter.WriteObjectValue(this);
            return content;
        }
    }
}
