// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using System.Linq;

namespace Microsoft.PowerBI.Api.Models
{
    /// <summary> A request for migrating workspaces to a shared capacity as tenant admin. </summary>
    public partial class UnassignWorkspacesCapacityRequest
    {
        /// <summary> Initializes a new instance of <see cref="UnassignWorkspacesCapacityRequest"/>. </summary>
        /// <param name="workspacesToUnassign"> The workspaces to migrate to a shared capacity. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="workspacesToUnassign"/> is null. </exception>
        public UnassignWorkspacesCapacityRequest(IEnumerable<string> workspacesToUnassign)
        {
            Argument.AssertNotNull(workspacesToUnassign, nameof(workspacesToUnassign));

            WorkspacesToUnassign = workspacesToUnassign.ToList();
        }

        /// <summary> Initializes a new instance of <see cref="UnassignWorkspacesCapacityRequest"/>. </summary>
        /// <param name="workspacesToUnassign"> The workspaces to migrate to a shared capacity. </param>
        internal UnassignWorkspacesCapacityRequest(IList<string> workspacesToUnassign)
        {
            WorkspacesToUnassign = workspacesToUnassign;
        }

        /// <summary> The workspaces to migrate to a shared capacity. </summary>
        public IList<string> WorkspacesToUnassign { get; }
    }
}
