// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace Microsoft.PowerBI.Api.Models
{
    /// <summary> The unused Power BI item entity. </summary>
    public partial class UnusedArtifactEntity
    {
        /// <summary> Initializes a new instance of <see cref="UnusedArtifactEntity"/>. </summary>
        /// <param name="artifactId"> The ID of the Power BI item. </param>
        /// <param name="displayName"> The display name of the Power BI item. </param>
        /// <param name="artifactType"> The Power BI item type. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="artifactId"/>, <paramref name="displayName"/> or <paramref name="artifactType"/> is null. </exception>
        internal UnusedArtifactEntity(string artifactId, string displayName, string artifactType)
        {
            Argument.AssertNotNull(artifactId, nameof(artifactId));
            Argument.AssertNotNull(displayName, nameof(displayName));
            Argument.AssertNotNull(artifactType, nameof(artifactType));

            ArtifactId = artifactId;
            DisplayName = displayName;
            ArtifactType = artifactType;
        }

        /// <summary> Initializes a new instance of <see cref="UnusedArtifactEntity"/>. </summary>
        /// <param name="artifactId"> The ID of the Power BI item. </param>
        /// <param name="displayName"> The display name of the Power BI item. </param>
        /// <param name="artifactType"> The Power BI item type. </param>
        /// <param name="artifactSizeInMB"> The size of the Power BI item in megabytes (if applicable). </param>
        /// <param name="createdDateTime"> The creation time of the Power BI item (if applicable). </param>
        /// <param name="lastAccessedDateTime"> The last access time of the Power BI item (if applicable). </param>
        internal UnusedArtifactEntity(string artifactId, string displayName, string artifactType, int? artifactSizeInMB, DateTimeOffset? createdDateTime, DateTimeOffset? lastAccessedDateTime)
        {
            ArtifactId = artifactId;
            DisplayName = displayName;
            ArtifactType = artifactType;
            ArtifactSizeInMB = artifactSizeInMB;
            CreatedDateTime = createdDateTime;
            LastAccessedDateTime = lastAccessedDateTime;
        }

        /// <summary> The ID of the Power BI item. </summary>
        public string ArtifactId { get; }
        /// <summary> The display name of the Power BI item. </summary>
        public string DisplayName { get; }
        /// <summary> The Power BI item type. </summary>
        public string ArtifactType { get; }
        /// <summary> The size of the Power BI item in megabytes (if applicable). </summary>
        public int? ArtifactSizeInMB { get; }
        /// <summary> The creation time of the Power BI item (if applicable). </summary>
        public DateTimeOffset? CreatedDateTime { get; }
        /// <summary> The last access time of the Power BI item (if applicable). </summary>
        public DateTimeOffset? LastAccessedDateTime { get; }
    }
}
