// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace Microsoft.PowerBI.Api.Models
{
    /// <summary> The update details for a Power BI dataset parameter. </summary>
    public partial class UpdateMashupParameterDetails
    {
        /// <summary> Initializes a new instance of <see cref="UpdateMashupParameterDetails"/>. </summary>
        /// <param name="name"> The parameter name. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="name"/> is null. </exception>
        public UpdateMashupParameterDetails(string name)
        {
            Argument.AssertNotNull(name, nameof(name));

            Name = name;
        }

        /// <summary> Initializes a new instance of <see cref="UpdateMashupParameterDetails"/>. </summary>
        /// <param name="name"> The parameter name. </param>
        /// <param name="newValue"> The new value for the parameter. </param>
        internal UpdateMashupParameterDetails(string name, string newValue)
        {
            Name = name;
            NewValue = newValue;
        }

        /// <summary> The parameter name. </summary>
        public string Name { get; }
        /// <summary> The new value for the parameter. </summary>
        public string NewValue { get; set; }
    }
}
