// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Microsoft.PowerBI.Api.Models
{
    /// <summary> A request to update an existing deployment pipeline. An updated display name and/or a description is required. </summary>
    public partial class UpdatePipelineRequest
    {
        /// <summary> Initializes a new instance of <see cref="UpdatePipelineRequest"/>. </summary>
        public UpdatePipelineRequest()
        {
        }

        /// <summary> Initializes a new instance of <see cref="UpdatePipelineRequest"/>. </summary>
        /// <param name="displayName"> The updated display name for the deployment pipeline. </param>
        /// <param name="description"> The updated description for the deployment pipeline. </param>
        internal UpdatePipelineRequest(string displayName, string description)
        {
            DisplayName = displayName;
            Description = description;
        }

        /// <summary> The updated display name for the deployment pipeline. </summary>
        public string DisplayName { get; set; }
        /// <summary> The updated description for the deployment pipeline. </summary>
        public string Description { get; set; }
    }
}
