// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Microsoft.PowerBI.Api.Models
{
    /// <summary> An update request for the group. </summary>
    public partial class UpdateGroupRequest
    {
        /// <summary> Initializes a new instance of <see cref="UpdateGroupRequest"/>. </summary>
        public UpdateGroupRequest()
        {
        }

        /// <summary> Initializes a new instance of <see cref="UpdateGroupRequest"/>. </summary>
        /// <param name="name"> The group name. </param>
        /// <param name="defaultDatasetStorageFormat"> The default dataset storage format in the group. </param>
        internal UpdateGroupRequest(string name, DefaultDatasetStorageFormat? defaultDatasetStorageFormat)
        {
            Name = name;
            DefaultDatasetStorageFormat = defaultDatasetStorageFormat;
        }

        /// <summary> The group name. </summary>
        public string Name { get; set; }
        /// <summary> The default dataset storage format in the group. </summary>
        public DefaultDatasetStorageFormat? DefaultDatasetStorageFormat { get; set; }
    }
}
