// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;

namespace Microsoft.PowerBI.Api.Models
{
    /// <summary> Workspace info response. </summary>
    public partial class WorkspaceInfoResponse
    {
        /// <summary> Initializes a new instance of <see cref="WorkspaceInfoResponse"/>. </summary>
        internal WorkspaceInfoResponse()
        {
            Workspaces = new ChangeTrackingList<WorkspaceInfo>();
            DatasourceInstances = new ChangeTrackingList<Datasource>();
            MisconfiguredDatasourceInstances = new ChangeTrackingList<Datasource>();
        }

        /// <summary> Initializes a new instance of <see cref="WorkspaceInfoResponse"/>. </summary>
        /// <param name="workspaces"> The workspace info associated with this scan. </param>
        /// <param name="datasourceInstances"> The data source instances associated with this scan. </param>
        /// <param name="misconfiguredDatasourceInstances"> The data source misconfigured instances associated with this scan. </param>
        internal WorkspaceInfoResponse(IReadOnlyList<WorkspaceInfo> workspaces, IReadOnlyList<Datasource> datasourceInstances, IReadOnlyList<Datasource> misconfiguredDatasourceInstances)
        {
            Workspaces = workspaces;
            DatasourceInstances = datasourceInstances;
            MisconfiguredDatasourceInstances = misconfiguredDatasourceInstances;
        }

        /// <summary> The workspace info associated with this scan. </summary>
        public IReadOnlyList<WorkspaceInfo> Workspaces { get; }
        /// <summary> The data source instances associated with this scan. </summary>
        public IReadOnlyList<Datasource> DatasourceInstances { get; }
        /// <summary> The data source misconfigured instances associated with this scan. </summary>
        public IReadOnlyList<Datasource> MisconfiguredDatasourceInstances { get; }
    }
}
