// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;

namespace Microsoft.PowerBI.Api.Models
{
    /// <summary> The OData response wrapper for a Power BI dashboard collection. </summary>
    internal partial class WorkspaceInfoDashboards
    {
        /// <summary> Initializes a new instance of <see cref="WorkspaceInfoDashboards"/>. </summary>
        internal WorkspaceInfoDashboards()
        {
            Value = new ChangeTrackingList<WorkspaceInfoDashboard>();
        }

        /// <summary> Initializes a new instance of <see cref="WorkspaceInfoDashboards"/>. </summary>
        /// <param name="odataContext"> OData context. </param>
        /// <param name="value"> The dashboard collection. </param>
        internal WorkspaceInfoDashboards(string odataContext, IReadOnlyList<WorkspaceInfoDashboard> value)
        {
            OdataContext = odataContext;
            Value = value;
        }

        /// <summary> OData context. </summary>
        public string OdataContext { get; }
        /// <summary> The dashboard collection. </summary>
        public IReadOnlyList<WorkspaceInfoDashboard> Value { get; }
    }
}
