// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;

namespace Microsoft.PowerBI.Api.Models
{
    /// <summary> A Power BI datamart returned by Workspace Info APIs. The API returns a subset of the following list of datamart properties. The subset depends on the API called, caller permissions, and the availability of data in the Power BI database. </summary>
    public partial class WorkspaceInfoDatamart : DatamartBaseProperties
    {
        /// <summary> Initializes a new instance of <see cref="WorkspaceInfoDatamart"/>. </summary>
        /// <param name="id"> The datamart ID. </param>
        internal WorkspaceInfoDatamart(Guid id) : base(id)
        {
            UpstreamDataflows = new ChangeTrackingList<DependentDataflow>();
            UpstreamDatamarts = new ChangeTrackingList<DependentDatamart>();
            DatasourceUsages = new ChangeTrackingList<DatasourceUsage>();
            Users = new ChangeTrackingList<DatamartUser>();
        }

        /// <summary> Initializes a new instance of <see cref="WorkspaceInfoDatamart"/>. </summary>
        /// <param name="id"> The datamart ID. </param>
        /// <param name="name"> The datamart name. </param>
        /// <param name="description"> The datamart description. </param>
        /// <param name="type"> The datamart type. </param>
        /// <param name="status"> The datamart status. </param>
        /// <param name="state"> The datamart current state. </param>
        /// <param name="suspendedBatchId"> datamart suspended batch id. </param>
        /// <param name="endorsementDetails"> The datamart endorsement details. </param>
        /// <param name="sensitivityLabel"> The datamart sensitivity label. </param>
        /// <param name="modifiedBy"> The last user that modified the datamart. </param>
        /// <param name="modifiedDateTime"> The date and time that the datamart was last modified. </param>
        /// <param name="configuredBy"> The name of the datamart owner. </param>
        /// <param name="modifiedById"> The ID of the last user that modified the datamart. </param>
        /// <param name="configuredById"> The ID of the datamart owner. </param>
        /// <param name="upstreamDataflows"> The list of all the dataflows this item depends on. </param>
        /// <param name="upstreamDatamarts"> The list of all the datamarts this item depends on. </param>
        /// <param name="datasourceUsages"> The data source usages. </param>
        /// <param name="users"> The user access details for a Power BI datamart. </param>
        internal WorkspaceInfoDatamart(Guid id, string name, string description, DatamartType? type, DatamartStatus? status, DatamartState? state, string suspendedBatchId, EndorsementDetails endorsementDetails, SensitivityLabel sensitivityLabel, string modifiedBy, DateTimeOffset? modifiedDateTime, string configuredBy, string modifiedById, string configuredById, IReadOnlyList<DependentDataflow> upstreamDataflows, IReadOnlyList<DependentDatamart> upstreamDatamarts, IReadOnlyList<DatasourceUsage> datasourceUsages, IReadOnlyList<DatamartUser> users) : base(id, name, description, type, status, state, suspendedBatchId)
        {
            EndorsementDetails = endorsementDetails;
            SensitivityLabel = sensitivityLabel;
            ModifiedBy = modifiedBy;
            ModifiedDateTime = modifiedDateTime;
            ConfiguredBy = configuredBy;
            ModifiedById = modifiedById;
            ConfiguredById = configuredById;
            UpstreamDataflows = upstreamDataflows;
            UpstreamDatamarts = upstreamDatamarts;
            DatasourceUsages = datasourceUsages;
            Users = users;
        }

        /// <summary> The datamart endorsement details. </summary>
        public EndorsementDetails EndorsementDetails { get; }
        /// <summary> The datamart sensitivity label. </summary>
        public SensitivityLabel SensitivityLabel { get; }
        /// <summary> The last user that modified the datamart. </summary>
        public string ModifiedBy { get; }
        /// <summary> The date and time that the datamart was last modified. </summary>
        public DateTimeOffset? ModifiedDateTime { get; }
        /// <summary> The name of the datamart owner. </summary>
        public string ConfiguredBy { get; }
        /// <summary> The ID of the last user that modified the datamart. </summary>
        public string ModifiedById { get; }
        /// <summary> The ID of the datamart owner. </summary>
        public string ConfiguredById { get; }
        /// <summary> The list of all the dataflows this item depends on. </summary>
        public IReadOnlyList<DependentDataflow> UpstreamDataflows { get; }
        /// <summary> The list of all the datamarts this item depends on. </summary>
        public IReadOnlyList<DependentDatamart> UpstreamDatamarts { get; }
        /// <summary> The data source usages. </summary>
        public IReadOnlyList<DatasourceUsage> DatasourceUsages { get; }
        /// <summary> The user access details for a Power BI datamart. </summary>
        public IReadOnlyList<DatamartUser> Users { get; }
    }
}
