// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;

namespace Microsoft.PowerBI.Api.Models
{
    /// <summary> OData response wrapper for capacity workload settings list. </summary>
    public partial class Workloads
    {
        /// <summary> Initializes a new instance of <see cref="Workloads"/>. </summary>
        internal Workloads()
        {
            Value = new ChangeTrackingList<Workload>();
        }

        /// <summary> Initializes a new instance of <see cref="Workloads"/>. </summary>
        /// <param name="odataContext"></param>
        /// <param name="value"> The list of capacity workload settings. </param>
        internal Workloads(string odataContext, IReadOnlyList<Workload> value)
        {
            OdataContext = odataContext;
            Value = value;
        }

        /// <summary> Gets the odata context. </summary>
        public string OdataContext { get; }
        /// <summary> The list of capacity workload settings. </summary>
        public IReadOnlyList<Workload> Value { get; }
    }
}
