// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Threading;
using System.Threading.Tasks;
using Azure;
using Azure.Core;
using Azure.Core.Pipeline;
using Microsoft.PowerBI.Api.Models;

namespace Microsoft.PowerBI.Api
{
    /// <summary> The Scorecards service client. </summary>
    public partial class ScorecardsClient
    {
        private readonly ClientDiagnostics _clientDiagnostics;
        private readonly HttpPipeline _pipeline;
        internal ScorecardsRestClient RestClient { get; }

        /// <summary> Initializes a new instance of ScorecardsClient for mocking. </summary>
        protected ScorecardsClient()
        {
        }

        /// <summary> Initializes a new instance of ScorecardsClient. </summary>
        /// <param name="credential"> A credential used to authenticate to an Azure Service. </param>
        /// <param name="endpoint"> server parameter. </param>
        /// <param name="options"> The options for configuring the client. </param>
        public ScorecardsClient(TokenCredential credential, Uri endpoint = null, PowerBIClientOptions options = null)
        {
            if (credential == null)
            {
                throw new ArgumentNullException(nameof(credential));
            }
            endpoint ??= new Uri("https://api.powerbi.com");

            options ??= new PowerBIClientOptions();
            _clientDiagnostics = new ClientDiagnostics(options);
            string[] scopes = { "https://analysis.windows.net/powerbi/api/.default" };
            _pipeline = HttpPipelineBuilder.Build(options, new BearerTokenAuthenticationPolicy(credential, scopes));
            RestClient = new ScorecardsRestClient(_clientDiagnostics, _pipeline, endpoint);
        }

        /// <summary> Initializes a new instance of ScorecardsClient. </summary>
        /// <param name="clientDiagnostics"> The handler for diagnostic messaging in the client. </param>
        /// <param name="pipeline"> The HTTP pipeline for sending and receiving REST requests and responses. </param>
        /// <param name="endpoint"> server parameter. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="clientDiagnostics"/> or <paramref name="pipeline"/> is null. </exception>
        internal ScorecardsClient(ClientDiagnostics clientDiagnostics, HttpPipeline pipeline, Uri endpoint = null)
        {
            RestClient = new ScorecardsRestClient(clientDiagnostics, pipeline, endpoint);
            _clientDiagnostics = clientDiagnostics;
            _pipeline = pipeline;
        }

        /// <summary> Returns a list of scorecards from a workspace. </summary>
        /// <param name="groupId"> The unique identifier of the workspace. </param>
        /// <param name="top"> Returns only the first n results. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        /// <remarks>
        /// ## Required Scope
        ///
        /// Dataset.Read.All or Dataset.ReadWrite.All
        /// &lt;br&gt;&lt;br&gt;
        /// </remarks>
        public virtual async Task<Response<Scorecards>> PreviewGetAsync(Guid groupId, int? top = null, CancellationToken cancellationToken = default)
        {
            using var scope = _clientDiagnostics.CreateScope("ScorecardsClient.PreviewGet");
            scope.Start();
            try
            {
                return await RestClient.PreviewGetAsync(groupId, top, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception e)
            {
                scope.Failed(e);
                throw;
            }
        }

        /// <summary> Returns a list of scorecards from a workspace. </summary>
        /// <param name="groupId"> The unique identifier of the workspace. </param>
        /// <param name="top"> Returns only the first n results. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        /// <remarks>
        /// ## Required Scope
        ///
        /// Dataset.Read.All or Dataset.ReadWrite.All
        /// &lt;br&gt;&lt;br&gt;
        /// </remarks>
        public virtual Response<Scorecards> PreviewGet(Guid groupId, int? top = null, CancellationToken cancellationToken = default)
        {
            using var scope = _clientDiagnostics.CreateScope("ScorecardsClient.PreviewGet");
            scope.Start();
            try
            {
                return RestClient.PreviewGet(groupId, top, cancellationToken);
            }
            catch (Exception e)
            {
                scope.Failed(e);
                throw;
            }
        }

        /// <summary> Creates a new scorecard. </summary>
        /// <param name="groupId"> The unique identifier of the workspace. </param>
        /// <param name="scorecard"> The new scorecard properties. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        /// <remarks>
        /// ## Required Scope
        ///
        /// Dataset.ReadWrite.All
        /// &lt;br&gt;&lt;br&gt;
        /// </remarks>
        public virtual async Task<Response<Scorecard>> PreviewPostAsync(Guid groupId, ScorecardCreateRequest scorecard, CancellationToken cancellationToken = default)
        {
            using var scope = _clientDiagnostics.CreateScope("ScorecardsClient.PreviewPost");
            scope.Start();
            try
            {
                return await RestClient.PreviewPostAsync(groupId, scorecard, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception e)
            {
                scope.Failed(e);
                throw;
            }
        }

        /// <summary> Creates a new scorecard. </summary>
        /// <param name="groupId"> The unique identifier of the workspace. </param>
        /// <param name="scorecard"> The new scorecard properties. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        /// <remarks>
        /// ## Required Scope
        ///
        /// Dataset.ReadWrite.All
        /// &lt;br&gt;&lt;br&gt;
        /// </remarks>
        public virtual Response<Scorecard> PreviewPost(Guid groupId, ScorecardCreateRequest scorecard, CancellationToken cancellationToken = default)
        {
            using var scope = _clientDiagnostics.CreateScope("ScorecardsClient.PreviewPost");
            scope.Start();
            try
            {
                return RestClient.PreviewPost(groupId, scorecard, cancellationToken);
            }
            catch (Exception e)
            {
                scope.Failed(e);
                throw;
            }
        }

        /// <summary> Returns a scorecard with ID. </summary>
        /// <param name="groupId"> The unique identifier of the workspace. </param>
        /// <param name="scorecardId"> The unique identifier of the scorecard. </param>
        /// <param name="expand"> Accepts a comma-separated list of data types, which will be expanded inline in the response. Supports `goals`, `goalValues`, `aggregations`, and `notes`. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        /// <remarks>
        /// ## Required Scope
        ///
        /// Dataset.Read.All or Dataset.ReadWrite.All
        /// &lt;br&gt;&lt;br&gt;
        /// </remarks>
        public virtual async Task<Response<Scorecard>> PreviewGetByIDAsync(Guid groupId, Guid scorecardId, string expand = null, CancellationToken cancellationToken = default)
        {
            using var scope = _clientDiagnostics.CreateScope("ScorecardsClient.PreviewGetByID");
            scope.Start();
            try
            {
                return await RestClient.PreviewGetByIDAsync(groupId, scorecardId, expand, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception e)
            {
                scope.Failed(e);
                throw;
            }
        }

        /// <summary> Returns a scorecard with ID. </summary>
        /// <param name="groupId"> The unique identifier of the workspace. </param>
        /// <param name="scorecardId"> The unique identifier of the scorecard. </param>
        /// <param name="expand"> Accepts a comma-separated list of data types, which will be expanded inline in the response. Supports `goals`, `goalValues`, `aggregations`, and `notes`. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        /// <remarks>
        /// ## Required Scope
        ///
        /// Dataset.Read.All or Dataset.ReadWrite.All
        /// &lt;br&gt;&lt;br&gt;
        /// </remarks>
        public virtual Response<Scorecard> PreviewGetByID(Guid groupId, Guid scorecardId, string expand = null, CancellationToken cancellationToken = default)
        {
            using var scope = _clientDiagnostics.CreateScope("ScorecardsClient.PreviewGetByID");
            scope.Start();
            try
            {
                return RestClient.PreviewGetByID(groupId, scorecardId, expand, cancellationToken);
            }
            catch (Exception e)
            {
                scope.Failed(e);
                throw;
            }
        }

        /// <summary> Updates a scorecard by its ID. </summary>
        /// <param name="groupId"> The unique identifier of the workspace. </param>
        /// <param name="scorecardId"> The unique identifier of the scorecard. </param>
        /// <param name="scorecard"> The scorecard properties to patch. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        /// <remarks>
        /// ## Required Scope
        ///
        /// Dataset.ReadWrite.All
        /// &lt;br&gt;&lt;br&gt;
        /// </remarks>
        public virtual async Task<Response<Scorecard>> PreviewPatchByIDAsync(Guid groupId, Guid scorecardId, Scorecard scorecard, CancellationToken cancellationToken = default)
        {
            using var scope = _clientDiagnostics.CreateScope("ScorecardsClient.PreviewPatchByID");
            scope.Start();
            try
            {
                return await RestClient.PreviewPatchByIDAsync(groupId, scorecardId, scorecard, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception e)
            {
                scope.Failed(e);
                throw;
            }
        }

        /// <summary> Updates a scorecard by its ID. </summary>
        /// <param name="groupId"> The unique identifier of the workspace. </param>
        /// <param name="scorecardId"> The unique identifier of the scorecard. </param>
        /// <param name="scorecard"> The scorecard properties to patch. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        /// <remarks>
        /// ## Required Scope
        ///
        /// Dataset.ReadWrite.All
        /// &lt;br&gt;&lt;br&gt;
        /// </remarks>
        public virtual Response<Scorecard> PreviewPatchByID(Guid groupId, Guid scorecardId, Scorecard scorecard, CancellationToken cancellationToken = default)
        {
            using var scope = _clientDiagnostics.CreateScope("ScorecardsClient.PreviewPatchByID");
            scope.Start();
            try
            {
                return RestClient.PreviewPatchByID(groupId, scorecardId, scorecard, cancellationToken);
            }
            catch (Exception e)
            {
                scope.Failed(e);
                throw;
            }
        }

        /// <summary> Deletes a scorecard by its ID. </summary>
        /// <param name="groupId"> The unique identifier of the workspace. </param>
        /// <param name="scorecardId"> The unique identifier of the scorecard. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        /// <remarks>
        /// ## Required Scope
        ///
        /// Dataset.ReadWrite.All
        /// &lt;br&gt;&lt;br&gt;
        /// </remarks>
        public virtual async Task<Response> PreviewDeleteByIDAsync(Guid groupId, Guid scorecardId, CancellationToken cancellationToken = default)
        {
            using var scope = _clientDiagnostics.CreateScope("ScorecardsClient.PreviewDeleteByID");
            scope.Start();
            try
            {
                return await RestClient.PreviewDeleteByIDAsync(groupId, scorecardId, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception e)
            {
                scope.Failed(e);
                throw;
            }
        }

        /// <summary> Deletes a scorecard by its ID. </summary>
        /// <param name="groupId"> The unique identifier of the workspace. </param>
        /// <param name="scorecardId"> The unique identifier of the scorecard. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        /// <remarks>
        /// ## Required Scope
        ///
        /// Dataset.ReadWrite.All
        /// &lt;br&gt;&lt;br&gt;
        /// </remarks>
        public virtual Response PreviewDeleteByID(Guid groupId, Guid scorecardId, CancellationToken cancellationToken = default)
        {
            using var scope = _clientDiagnostics.CreateScope("ScorecardsClient.PreviewDeleteByID");
            scope.Start();
            try
            {
                return RestClient.PreviewDeleteByID(groupId, scorecardId, cancellationToken);
            }
            catch (Exception e)
            {
                scope.Failed(e);
                throw;
            }
        }

        /// <summary> Reads a scorecard associated with an internal report ID. </summary>
        /// <param name="groupId"> The unique identifier of the workspace. </param>
        /// <param name="reportId"> The ID of the internal report associated with the scorecard. </param>
        /// <param name="expand"> Accepts a comma-separated list of data types, which will be expanded inline in the response. Supports `goals`, `goalValues`, and `aggregations`. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        /// <remarks>
        /// ## Required Scope
        ///
        /// Dataset.Read.All or Dataset.ReadWrite.All
        /// &lt;br&gt;&lt;br&gt;
        /// </remarks>
        public virtual async Task<Response<Scorecard>> PreviewGetScorecardByReportIdAsync(Guid groupId, Guid reportId, string expand = null, CancellationToken cancellationToken = default)
        {
            using var scope = _clientDiagnostics.CreateScope("ScorecardsClient.PreviewGetScorecardByReportId");
            scope.Start();
            try
            {
                return await RestClient.PreviewGetScorecardByReportIdAsync(groupId, reportId, expand, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception e)
            {
                scope.Failed(e);
                throw;
            }
        }

        /// <summary> Reads a scorecard associated with an internal report ID. </summary>
        /// <param name="groupId"> The unique identifier of the workspace. </param>
        /// <param name="reportId"> The ID of the internal report associated with the scorecard. </param>
        /// <param name="expand"> Accepts a comma-separated list of data types, which will be expanded inline in the response. Supports `goals`, `goalValues`, and `aggregations`. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        /// <remarks>
        /// ## Required Scope
        ///
        /// Dataset.Read.All or Dataset.ReadWrite.All
        /// &lt;br&gt;&lt;br&gt;
        /// </remarks>
        public virtual Response<Scorecard> PreviewGetScorecardByReportId(Guid groupId, Guid reportId, string expand = null, CancellationToken cancellationToken = default)
        {
            using var scope = _clientDiagnostics.CreateScope("ScorecardsClient.PreviewGetScorecardByReportId");
            scope.Start();
            try
            {
                return RestClient.PreviewGetScorecardByReportId(groupId, reportId, expand, cancellationToken);
            }
            catch (Exception e)
            {
                scope.Failed(e);
                throw;
            }
        }

        /// <summary> Moves goals within the scorecard. Changes their ranks and parents. </summary>
        /// <param name="groupId"> The unique identifier of the workspace. </param>
        /// <param name="scorecardId"> The unique identifier of the scorecard. </param>
        /// <param name="moveGoalsRequest"> The request describing the move operation. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        /// <remarks>
        /// ## Required Scope
        ///
        /// Dataset.ReadWrite.All
        /// &lt;br&gt;&lt;br&gt;
        /// </remarks>
        public virtual async Task<Response> PreviewMoveGoalsAsync(Guid groupId, Guid scorecardId, GoalsMoveRequest moveGoalsRequest, CancellationToken cancellationToken = default)
        {
            using var scope = _clientDiagnostics.CreateScope("ScorecardsClient.PreviewMoveGoals");
            scope.Start();
            try
            {
                return await RestClient.PreviewMoveGoalsAsync(groupId, scorecardId, moveGoalsRequest, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception e)
            {
                scope.Failed(e);
                throw;
            }
        }

        /// <summary> Moves goals within the scorecard. Changes their ranks and parents. </summary>
        /// <param name="groupId"> The unique identifier of the workspace. </param>
        /// <param name="scorecardId"> The unique identifier of the scorecard. </param>
        /// <param name="moveGoalsRequest"> The request describing the move operation. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        /// <remarks>
        /// ## Required Scope
        ///
        /// Dataset.ReadWrite.All
        /// &lt;br&gt;&lt;br&gt;
        /// </remarks>
        public virtual Response PreviewMoveGoals(Guid groupId, Guid scorecardId, GoalsMoveRequest moveGoalsRequest, CancellationToken cancellationToken = default)
        {
            using var scope = _clientDiagnostics.CreateScope("ScorecardsClient.PreviewMoveGoals");
            scope.Start();
            try
            {
                return RestClient.PreviewMoveGoals(groupId, scorecardId, moveGoalsRequest, cancellationToken);
            }
            catch (Exception e)
            {
                scope.Failed(e);
                throw;
            }
        }
    }
}
